export interface CatalogItem {
  slug: string;
  title: string;
  category: "WebMCP" | "Interaction" | "MCP" | "Foundation";
  description: string;
  files: string[];
  exports: string[];
  props: [string, string, string][];
  note: string;
}
const item = (
  slug: string,
  title: string,
  category: CatalogItem["category"],
  description: string,
  files: string[],
  exports: string[],
  props: CatalogItem["props"],
  note = "",
): CatalogItem => ({
  slug,
  title,
  category,
  description,
  files,
  exports,
  props,
  note,
});
export const catalog: CatalogItem[] = [
  item(
    "webmcp-provider",
    "WebMCP provider",
    "WebMCP",
    "Give your interface a shared home for tools, state and agent activity.",
    ["registry/webmcp/provider.tsx"],
    ["WebMCPProvider", "useWebMCP", "useWebMCPTool"],
    [["children", "ReactNode", "Wrap the interactive area of your page."]],
    "Registrations are scoped to component lifetime. Human controls work in browsers without WebMCP. Native registration failures are exposed through useWebMCP().error.",
  ),
  item(
    "webmcp-form",
    "Agent-ready form",
    "WebMCP",
    "Semantic forms that people and browser agents can fill together.",
    ["registry/webmcp/form.tsx"],
    ["WebMCPForm", "toolField"],
    [
      ["toolName", "string", "Unique declarative tool name."],
      [
        "toolDescription",
        "string",
        "Explain the outcome of submitting this form.",
      ],
      [
        "autoSubmit",
        "boolean = false",
        "Allow the agent to submit without a manual review.",
      ],
      [
        "onExecute",
        "(FormData, context) => Promise<unknown>",
        "Shared submit handler and structured result.",
      ],
    ],
    "Uses toolname/tooldescription HTML attributes and feature-detected SubmitEvent.respondWith. Use native named controls. Do not also register an imperative tool with the same name.",
  ),
  item(
    "support-badge",
    "Browser support",
    "WebMCP",
    "Show native support, legacy compatibility or manual mode.",
    ["registry/components/support-badge.tsx"],
    ["SupportBadge"],
    [
      ["support", "Support", "checking, native, legacy or unsupported."],
      ["error", "string?", "Optional registration error."],
    ],
    "Native support is feature-detected. A supported browser may still require an origin trial or testing flag.",
  ),
  item(
    "action-button",
    "Action button",
    "Interaction",
    "A single action with pending, error and duplicate-click handling.",
    ["registry/components/action-button.tsx"],
    ["ActionButton"],
    [
      ["action", "() => Promise<unknown>", "Action to run."],
      ["children", "ReactNode", "Visible accessible button label."],
      ["disabled", "boolean", "Disable when unavailable."],
    ],
    "For WebMCP, pass the same useWebMCP().run call used by the tool interface.",
  ),
  item(
    "arguments-form",
    "Arguments form",
    "Interaction",
    "Turn a tool schema into a usable form, with a JSON escape hatch.",
    ["registry/components/arguments-form.tsx"],
    ["ArgumentsForm"],
    [
      ["schema", "JsonSchema", "Self-contained JSON Schema 2020-12."],
      [
        "onSubmit",
        "(args) => Promise<unknown>",
        "Receives validated arguments.",
      ],
      ["initialValues", "Record<string, unknown>", "Initial input values."],
      ["submitLabel", "string", "Submit action label."],
    ],
    "Simple scalar object schemas become fields. Composed, nested and array schemas use JSON editing. AJV validates both paths; unresolved external references fail explicitly.",
  ),
  item(
    "data-explorer",
    "Data explorer",
    "Interaction",
    "Search, filter, sort and select records with one shared state.",
    ["registry/components/data-explorer.tsx"],
    ["SearchFilter", "DataTable"],
    [
      ["rows", "T[]", "Filtered records, each with a stable id."],
      [
        "columns",
        "DataColumn<T>[]",
        "Labels, keys and optional cell renderers.",
      ],
      ["selected", "string[]", "Controlled row selection."],
      [
        "onSelectionChange",
        "(ids: string[]) => void",
        "Receive selected row IDs.",
      ],
      ["pageSize", "number = 5", "Number of records per page."],
    ],
    "SearchFilter uses controlled query/filter props. Sorting and pagination are local; register semantic tools to control your app state.",
  ),
  item(
    "date-range",
    "Date range",
    "Interaction",
    "Native date fields and an accessible calendar, working in tandem.",
    ["registry/components/date-range.tsx"],
    ["DateRangePicker"],
    [
      [
        "value",
        "{from: string; to: string}",
        "Calendar dates in YYYY-MM-DD format.",
      ],
      ["onChange", "(range) => void", "Controlled selection."],
      ["min", "string?", "Earliest selectable date."],
      ["required", "boolean", "Require native date fields."],
    ],
    "Dates represent calendar days without timezone conversion. Validate the full range again in your action handler.",
  ),
  item(
    "wizard",
    "Multi-step flow",
    "Interaction",
    "Guide a shared human-agent workflow through review and completion.",
    ["registry/components/wizard.tsx"],
    ["Wizard"],
    [
      [
        "steps",
        "WizardStep[]",
        "Title, content and optional async validation.",
      ],
      ["step", "number", "Controlled zero-based step."],
      ["onStepChange", "(step) => void", "Update the active step."],
      ["onComplete", "() => Promise<unknown>", "Completion action."],
    ],
    "Register a prepare tool to populate fields and advance to review. The final business operation belongs to your completion handler.",
  ),
  item(
    "confirmation-dialog",
    "Confirmation",
    "Interaction",
    "Give an action a clear review point before it runs.",
    ["registry/components/confirmation-dialog.tsx"],
    ["ConfirmationDialog"],
    [
      ["open", "boolean", "Controlled visibility."],
      ["onOpenChange", "(open) => void", "Visibility updates."],
      [
        "title / description",
        "string",
        "Describe the concrete action and its consequences.",
      ],
      ["onConfirm", "() => Promise<unknown>", "Runs only after confirmation."],
    ],
    "Focus trapping and dismissal come from Base UI. Pending actions cannot be dismissed accidentally.",
  ),
  item(
    "mcp-client",
    "MCP client",
    "Foundation",
    "Connect to the current protocol, with isolated legacy compatibility.",
    ["registry/mcp/provider.tsx", "registry/mcp/oauth.ts"],
    ["MCPProvider", "useMCPClient", "BrowserOAuthProvider"],
    [
      [
        "connect",
        "(ConnectionOptions) => Promise<void>",
        "Endpoint, authentication and version selection.",
      ],
      [
        "run",
        "(name, args) => Promise<unknown>",
        "Call a tool and record its execution.",
      ],
      [
        "disconnect",
        "() => Promise<void>",
        "Close streams and clear connection data.",
      ],
    ],
    "Uses official SDK v2 with auto negotiation, preferring 2026-07-28. Network failures are not treated as proof of an old server. Tasks, Skills and MCP Apps extensions are not advertised.",
  ),
  item(
    "connection-panel",
    "Connection panel",
    "MCP",
    "An endpoint, an auth method, and a clear connection state.",
    ["registry/components/connection-panel.tsx"],
    ["ConnectionPanel"],
    [
      ["status", "string", "Connection lifecycle state."],
      [
        "onConnect",
        "(ConnectionOptions) => Promise<void>",
        "Connect with the selected method.",
      ],
      ["onDisconnect", "() => Promise<void>", "Release the connection."],
      ["defaultEndpoint", "string?", "Initial endpoint URL."],
    ],
    "Bearer tokens stay in memory. OAuth requires callback and client metadata routes; see the authentication guide. CORS is controlled by the destination server.",
  ),
  item(
    "tool-catalog",
    "Tool catalog",
    "MCP",
    "Make tool discovery readable, searchable and keyboard accessible.",
    ["registry/components/tool-catalog.tsx"],
    ["ToolCatalog", "ToolDetail"],
    [
      ["tools", "ToolDefinition[]", "Available tool definitions."],
      ["selected", "string?", "Selected tool name."],
      ["onSelect", "(tool) => void", "Selection callback."],
    ],
    "Descriptions and annotation hints are untrusted server metadata, not a permission boundary.",
  ),
  item(
    "tool-detail",
    "Tool detail",
    "MCP",
    "A tool description, its arguments, and the action in one place.",
    ["registry/components/tool-catalog.tsx"],
    ["ToolDetail"],
    [
      ["tool", "ToolDefinition", "Tool metadata and input schema."],
      ["onRun", "(args) => Promise<unknown>", "Validated execution callback."],
      ["disabled", "boolean", "Whether execution is available."],
    ],
    "Each tool uses its own input schema. The schema can be inspected without executing the tool.",
  ),
  item(
    "result-view",
    "Result viewer",
    "MCP",
    "Readable text, structured content and media, with raw data one click away.",
    ["registry/components/result-view.tsx"],
    ["ResultView"],
    [
      ["result", "unknown", "Original MCP or application result."],
      ["className", "string?", "Additional styles."],
    ],
    "Renders text without HTML execution. Raster images and audio use bounded inline data. Unknown content remains inspectable as JSON. Resource links require HTTP(S).",
  ),
  item(
    "execution-log",
    "Execution history",
    "MCP",
    "Follow progress, inspect results, and cancel outstanding requests.",
    ["registry/components/execution-log.tsx"],
    ["ExecutionLog"],
    [
      ["executions", "Execution[]", "Newest-first execution records."],
      ["onCancel", "(id) => void", "Cancel the associated request."],
      ["onClear", "() => void", "Clear completed history."],
    ],
    "History is in memory and capped at 100 in the providers. Cancellation does not imply rollback. Failed mutations are never automatically replayed.",
  ),
  item(
    "elicitation-dialog",
    "Elicitation",
    "MCP",
    "Answer the server when a tool needs another piece of information.",
    ["registry/components/elicitation-dialog.tsx"],
    ["ElicitationDialog"],
    [["request", "Elicitation?", "Current form or URL-mode request."]],
    "The SDK fulfills 2026 input_required rounds through this handler. Declining or closing returns an explicit response; disconnect cancels outstanding prompts.",
  ),
  item(
    "resource-explorer",
    "Resources & prompts",
    "MCP",
    "Read resources, resolve templates, and fill reusable prompts.",
    ["registry/components/resource-explorer.tsx"],
    ["ResourceExplorer", "PromptCatalog"],
    [
      [
        "resources / templates",
        "Resource[] / ResourceTemplateType[]",
        "Discovered resources and URI templates.",
      ],
      [
        "onRead",
        "(uri) => Promise<unknown>",
        "Read a selected or fully expanded URI.",
      ],
      ["prompts", "Prompt[]", "Discovered prompt definitions."],
      ["onGet", "(name, args) => Promise<unknown>", "Resolve a prompt."],
    ],
    "Template input accepts a complete expanded URI. Missing capabilities remain explicit empty states.",
  ),
  item(
    "mcp-dashboard",
    "MCP dashboard",
    "MCP",
    "A complete working console, composed from the registry.",
    ["registry/components/mcp-dashboard.tsx"],
    ["MCPDashboard", "MCPDashboardContent"],
    [
      [
        "defaultEndpoint",
        "string?",
        "Initial endpoint for the connection panel.",
      ],
    ],
    "Includes its own MCPProvider. Use MCPDashboardContent inside an existing provider when you need to share the connection.",
  ),
  item(
    "server-connector",
    "Server connector",
    "Foundation",
    "An optional Node bridge for private credentials and endpoints without CORS.",
    ["registry/server/connector.ts"],
    ["createConnector"],
    [
      [
        "destinations",
        "Record<string, {endpoint}>",
        "Operator-controlled HTTPS endpoints.",
      ],
      ["allowedOrigins", "string[]", "Accepted application origins."],
      [
        "authenticate",
        "(Request) => Promise<{id}|null>",
        "Authenticate every incoming request.",
      ],
      [
        "credentials",
        "(userId, destination) => Promise<{accessToken?}>",
        "Inject a token from your server-side store.",
      ],
    ],
    "Node-only. DNS answers are checked and pinned; redirects and private addresses are rejected. OAuth token acquisition/storage belongs to the host, which injects access tokens. No arbitrary URL proxy is exposed.",
  ),
];
export const guides = [
  { slug: "introduction", title: "Introduction" },
  { slug: "installation", title: "Installation" },
  { slug: "webmcp", title: "WebMCP integration" },
  { slug: "authentication", title: "OAuth & connections" },
  { slug: "server", title: "Server connector" },
  { slug: "compatibility", title: "Compatibility" },
];
